# Generated by Django 4.0.6 on 2022-07-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mailAccounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100, null=True)),
                ('last_mail_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailLabel',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('lebel_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mailStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.mailaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='mailObject',
            fields=[
                ('archived', models.BooleanField(default=False)),
                ('mail_object_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_type', models.CharField(max_length=100, null=True)),
                ('system_mail', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('mail_label', models.CharField(max_length=100, null=True)),
                ('mail_server_id', models.IntegerField(null=True)),
                ('body', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.mailaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='mailHead',
            fields=[
                ('sender', models.CharField(max_length=100, null=True)),
                ('reply_to', models.CharField(max_length=100, null=True)),
                ('recipient', models.CharField(max_length=100, null=True)),
                ('recipient_email_address', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=700, null=True)),
                ('mail_date', models.CharField(max_length=100, null=True)),
                ('att_present', models.BooleanField(default=False)),
                ('mail_head_id', models.AutoField(primary_key=True, serialize=False)),
                ('mailObject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='v1.mailobject')),
            ],
        ),
        migrations.CreateModel(
            name='mailBody',
            fields=[
                ('mail_body_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_url', models.CharField(max_length=300, null=True)),
                ('body_draft_url', models.CharField(max_length=300, null=True)),
                ('mailHead', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='v1.mailhead')),
                ('mailObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.mailobject')),
            ],
        ),
        migrations.CreateModel(
            name='mailAttachments',
            fields=[
                ('mail_attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=400, null=True)),
                ('mailHead', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='v1.mailhead')),
            ],
        ),
    ]
