# Generated by Django 4.0.6 on 2022-09-22 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailAccounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_hostname', models.CharField(max_length=100)),
                ('account_host_engine_adress', models.CharField(max_length=100)),
                ('account_host_login_adress', models.CharField(max_length=100)),
                ('account_host_login_password', models.CharField(max_length=100)),
                ('account_inbox', models.IntegerField(default=0)),
                ('account_outbox', models.IntegerField(default=0)),
                ('account_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
