# Generated by Django 4.0.6 on 2022-09-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_usermailaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailobject',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.usermailaccounts'),
        ),
    ]
